# Obtención de status code
---

## Objetivo

* Obtener el status code (códigos numéricos de tres dígitos, ej. 200, 404) de cada una de las URLs de las instituciones universitarias argentinas. Al realizar una solicitud HTTP, el servidor web envía al navegador el código de estado para indicar si la conexión se establece correctamente.

## Funcionamiento

* **Entrada**: cada una de las URLs de las instituciones universitarias argentinas registradas en el archivo 'universidades-nombre-url.csv'
* **Proceso**: para cada URL se realiza una solicitud HTTP con la librería requests de Python.
* **Salida**: el código de estado de la respuesta (ejemplo: 200 si la página responde correctamente)

In [123]:
import requests
import pandas as pd

In [124]:
df = pd.read_csv('universidades-nombre-url.csv', sep=';')

In [125]:
df.head()

,Institución,URL
0,Instituto Universitario de Gendarmería Nacional,https://iugna.edu.ar
1,Instituto Universitario de la Policía Federal ...,https://www.iupfa.edu.ar
2,Instituto Universitario de Seguridad Marítima,https://iusm.edu.ar
3,Instituto Universitario Patagónico de las Artes,https://iupa.edu.ar/sitio/
4,Universidad Autónoma de Entre Ríos,https://www.uader.edu.ar/

In [126]:
# Función para obtener el status_code de cada URL
def get_status(url):
    try:
        response = requests.get(url, verify=False, timeout=5)
        return response.status_code
    except requests.exceptions.RequestException:
        return None  # Si hay error, devuelve None

In [127]:
df['status_code'] = df['URL'].apply(lambda url: get_status(url))

In [128]:
df

,Institución,URL,status_code
0,Instituto Universitario de Gendarmería Nacional,https://iugna.edu.ar,200.0
1,Instituto Universitario de la Policía Federal ...,https://www.iupfa.edu.ar,200.0
2,Instituto Universitario de Seguridad Marítima,https://iusm.edu.ar,200.0
3,Instituto Universitario Patagónico de las Artes,https://iupa.edu.ar/sitio/,200.0
4,Universidad Autónoma de Entre Ríos,https://www.uader.edu.ar/,200.0
...,...,...,...
137,Universidad Notarial Argentina,https://www.universidadnotarial.edu.ar/una/,200.0
138,Universidad Patagonia Argentina,https://upatagonia.edu.ar,200.0
139,Universidad Salesiana Argentina,https://www.unisal.edu.ar,200.0
140,Universidad Torcuato Di Tella,https://www.utdt.edu,200.0
141,Facultad Latinoamericana de Ciencias Sociales,https://www.flacso.org.ar/,200.0

In [129]:
df.to_csv('universidades-nombre-url-code.csv', sep=';', index=False)